import { redirect } from "next/navigation";
import { Wallet, TrendingUp } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatCurrency, formatMonth } from "@/lib/format";
import { StatCard } from "@/components/stat-card";
import { PayslipTable } from "@/components/payroll/payslip-table";
import { PayrollAdminTable } from "@/components/payroll/payroll-admin-table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default async function PayrollPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");

  const isAdmin = user.role === "ADMIN";

  const [myPayslips, allPayslips] = await Promise.all([
    prisma.payslip.findMany({
      where: { userId: user.id },
      orderBy: { month: "desc" },
    }),
    isAdmin
      ? prisma.payslip.findMany({
          orderBy: { month: "desc" },
          include: { user: { select: { id: true, name: true, department: true, jobTitle: true } } },
        })
      : Promise.resolve([]),
  ]);

  const latest = myPayslips[0];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Payroll</h1>
        <p className="mt-1 text-muted-foreground">
          Review your monthly payslips and salary breakdown.
        </p>
      </div>

      {latest && (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <StatCard
            icon={Wallet}
            label={`Latest net pay (${formatMonth(latest.month)})`}
            value={formatCurrency(latest.netPay)}
            hint={`Basic ${formatCurrency(latest.basicSalary)} + allowances ${formatCurrency(latest.allowances)}`}
          />
          <StatCard
            icon={TrendingUp}
            label="Payslips on record"
            value={String(myPayslips.length)}
            hint="Generated by HR each month"
          />
        </div>
      )}

      {isAdmin ? (
        <Tabs defaultValue="mine">
          <TabsList>
            <TabsTrigger value="mine">My Payroll</TabsTrigger>
            <TabsTrigger value="team">All Employees</TabsTrigger>
          </TabsList>
          <TabsContent value="mine" className="mt-4">
            <PayslipTable payslips={myPayslips} />
          </TabsContent>
          <TabsContent value="team" className="mt-4">
            <PayrollAdminTable payslips={allPayslips} />
          </TabsContent>
        </Tabs>
      ) : (
        <PayslipTable payslips={myPayslips} />
      )}
    </div>
  );
}
